### ISSUE TITLE
Renaming Suggestion of Method Names to Make Them More Descriptive

### ISSUE THREAD

**Issue by AnonymousAccount4SE** [oswaldobapvicjr/agents#52]
### Renaming Suggestion of Method Names to Make Them More Descriptive
---
**Description**
---

We have developed a tool (**NameSpotter**) for identifying non-descriptive method names, and using this tool we find a non-descriptive method name in your repository:
```java
/* Non-descriptive Method Name in src/main/java/net/obvj/agents/util/TimeInterval.java */
public static TimeInterval of (String input)
    {
        int digits = extractFirstDigitGroupFrom(input);
        String timeUnitDescription = extractFirstLetterGroupFrom(input);

        TimeUnit timeUnit = timeUnitDescription.isEmpty() ? TimeUnit.DEFAULT
                : TimeUnit.findByIdentifier(timeUnitDescription);

        return new TimeInterval(digits, timeUnit);
    }

```

We considered "of" as non-descriptive because it is too generic, and we can not infer the function of this method until we look into the method body or the comments above. We proposed renaming the method name to "parseString2TimeInterval". Consequently, when we look at this method name, we will be informed that this method is written for parsing a String input into a TimeInterval object.

Do you agree with the judgment? 

- If not, could you please leave your valuable opinion?

- If you do agree, the relevant modification has been submitted as a PR, and thanks for your precious time to consider it.

**Comment by oswaldobapvicjr** [comment]
@AnonymousAccount4SE, here are the reasons why your change is **_not_** approved:

1. The suggested name `parseString2TimeInterval` is **_redundant_**: by looking at the method signature, anyone can understand that the method accepts a **String** and returns a **TimeInterval**, so there's no point in repeating the parameter and return type in the method name. It just makes the coding mode verbose.
2. The method contains a Javadoc with some examples of accepted strings. So, your statement that the API users will have to look inside the method to understand what it does is not true. Every good IDE available in the community (e.g.: Eclipse, IntelliJ, etc.) will display the Javadoc when the user rests the mouse on the method name (here's the compiled Javadoc of the `TimeInterval` class: https://javadoc.io/static/net.obvj/agents/0.3.3/net/obvj/agents/util/TimeInterval.html)
4. The current method name is inspired by other well-known classes designed by **_leading programmers of the Java API_**. Here you have just a few examples:
   - **Duration**.of(...)
   - **Instant**.of(...)
   - **LocalDateTime**.of(...)
   - **Stream**.of(...)
   - **Optional**.of(...)
   - **CompletableFuture**.of(...)
5. Renaming a public method is not a simple task. Because this project is released on Maven Central, it may be a dependency for other projects too. So you don't just rename the method. Instead, you must **_deprecate_** it, and create a new one. That way, other API users will be notified that the old method may be removed soon, **without breaking their code**.

Good luck!
